hibernate.ddl-auto.mode: create-drop

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: zaqwsx
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    whitelabel:
      enabled: false